### PR TITLE
Fixes #7: add prometheus metrics

### LINKED ISSUE #7: Export Prometheus metrics
Study which metrics we could export so we can alert based on them. Ideas:

- Expiration time? 
- Secrets synced? 
- number of secrets that fail to sync
- total number of secrets managed by SecretsManager
- secret status (1 = synced, 0 = failed?). This metric would be exported multiple times, specifying in labels the secret name and namespace.

### PR DESCRIPTION
**Pull request by fllaca**
Fixes #13

### CODE REVIEW

File: backend/vault.go [hunk 1]
```diff
@@ -9,12 +9,25 @@ import (
...
+
+	"github.com/prometheus/client_golang/prometheus"
 )
 
 var logger *log.Logger
 
 const defaultSecretKey = "data"
 
+var (
+	tokenExpired = prometheus.NewGaugeVec(prometheus.GaugeOpts{
```
Comment (dannyk81) [inline backend/vault.go]: as discussed, I think exposing ttl and ttlmax as two separate metrics would allow us to write alerts when expiration is imminent.

wdyt?
