### PR TITLE
#47 separating scenarios in renewalLoop

### LINKED ISSUE #47: Missing return provokes wrong metrics delivery
We missed a return statement after the line 156 of the backend/vault.go file: 
* https://github.com/tuenti/secrets-manager/blob/master/backend/vault.go#L156

and this is provoking that we are sending successful login metrics when we shouldn't:

`c.logger.Info("login successful, got a new vault token")`

### PR DESCRIPTION
**Pull request by eduardogr**
fix #47

### CODE REVIEW

File: backend/vault.go [hunk 1]
```diff
@@ -154,14 +154,15 @@ func (c *client) renewalLoop() {
 		c.logger.Info("trying to login to vault again")
 		if err = c.vaultLogin(); err != nil {
 			vMetrics.updateVaultLoginErrorsTotalMetric()
```
Comment (dannyk81) [inline backend/vault.go]: should we log an error here? that we couldn't manage to login?

Comment (fcgravalos) [reply backend/vault.go]: I agree here :)

File: backend/vault.go [hunk 2]
```diff
@@ -154,14 +154,16 @@ func (c *client) renewalLoop() {
...
+			c.logger.Info("login error, vault token not obtained")
```
Comment (dannyk81) [inline backend/vault.go]: This should be an `Error` not `Info` and maybe also include the content of `err` to give more context?
